name: licensing-server

services:
  database:
    container_name: postgres
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: ${LS_DATABASE_USER}
      POSTGRES_PASSWORD: ${LS_DATABASE_PASSWORD}
      POSTGRES_DB: ${LS_DATABASE_DB}
    ports:
      - 5432:5432
    volumes:
      # seeding
      # - ./backend/database/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      # named volume
      - ls-pg-data:/var/lib/postgresql/data
volumes:
  ls-pg-data:
    external: true
