name: licensing-server

services:
  database:
    container_name: postgres
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      # seeding
      # - ./backend/database/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      # named volume
      - ls-pg-data:/var/lib/postgresql/data
  app:
    container_name: app
    hostname: api
    build:
      context: .
      target: ${APP_ENV}
      args:
        APP_HOME: ${APP_HOME}
    ports:
      - 8080:8080
    links:
      - database
    volumes:
      - ./:${APP_HOME}
  api:
    container_name: api
    image: cosmtrek/air
    working_dir: /
    ports:
      - 8080:8080
volumes:
  ls-pg-data:
    external: true
