// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {context} from '../models';

export function CreateToken(arg1:model.AuthRequest):Promise<model.DisplayAPIKey>;

export function DomReady(arg1:context.Context):Promise<void>;

export function Register(arg1:model.AuthRequest):Promise<model.User>;
