// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Auth() {
  return window['go']['backend']['App']['Auth']();
}

export function CreateToken(arg1) {
  return window['go']['backend']['App']['CreateToken'](arg1);
}

export function DomReady(arg1) {
  return window['go']['backend']['App']['DomReady'](arg1);
}

export function Register(arg1) {
  return window['go']['backend']['App']['Register'](arg1);
}
