// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateToken(arg1) {
  return window['go']['backend']['App']['CreateToken'](arg1);
}

export function DomReady(arg1) {
  return window['go']['backend']['App']['DomReady'](arg1);
}

export function Register(arg1) {
  return window['go']['backend']['App']['Register'](arg1);
}

export function SignIn() {
  return window['go']['backend']['App']['SignIn']();
}

export function SignOut() {
  return window['go']['backend']['App']['SignOut']();
}

export function WhoAmI() {
  return window['go']['backend']['App']['WhoAmI']();
}
