basePath: /api/v1
definitions:
  httputil.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
  httputil.HTTPResponse-model_APIKey:
    properties:
      data:
        $ref: '#/definitions/model.APIKey'
      message:
        type: string
    type: object
  httputil.HTTPResponse-model_User:
    properties:
      data:
        $ref: '#/definitions/model.User'
      message:
        type: string
    type: object
  model.APIKey:
    properties:
      created_at:
        type: integer
      deleted_at:
        type: integer
      id:
        type: string
      key:
        items:
          type: integer
        type: array
      scopes:
        type: string
      updated_at:
        type: integer
      user:
        $ref: '#/definitions/model.User'
      userId:
        type: string
    type: object
  model.License:
    properties:
      created_at:
        type: integer
      deleted_at:
        type: integer
      id:
        type: string
      product:
        $ref: '#/definitions/model.Product'
      product_id:
        type: string
      updated_at:
        type: integer
      user:
        $ref: '#/definitions/model.User'
      user_id:
        type: string
      value:
        type: string
    type: object
  model.Product:
    properties:
      created_at:
        type: integer
      deleted_at:
        type: integer
      id:
        type: string
      licenses:
        items:
          $ref: '#/definitions/model.License'
        type: array
      name:
        type: string
      rules:
        items:
          $ref: '#/definitions/model.Rule'
        type: array
      updated_at:
        type: integer
    type: object
  model.Rule:
    properties:
      created_at:
        type: integer
      deleted_at:
        type: integer
      id:
        type: string
      name:
        type: string
      products:
        items:
          $ref: '#/definitions/model.Product'
        type: array
      updated_at:
        type: integer
      user_groups:
        items:
          $ref: '#/definitions/model.UserGroup'
        type: array
      users:
        items:
          $ref: '#/definitions/model.User'
        type: array
    type: object
  model.User:
    properties:
      created_at:
        type: integer
      deleted_at:
        type: integer
      email:
        type: string
      groups:
        items:
          $ref: '#/definitions/model.UserGroup'
        type: array
      id:
        type: string
      name:
        type: string
      password:
        type: string
      rules:
        items:
          $ref: '#/definitions/model.Rule'
        type: array
      updated_at:
        type: integer
    required:
    - email
    type: object
  model.UserGroup:
    properties:
      created_at:
        type: integer
      deleted_at:
        type: integer
      id:
        type: string
      name:
        type: string
      rules:
        items:
          $ref: '#/definitions/model.Rule'
        type: array
      updated_at:
        type: integer
      users:
        items:
          $ref: '#/definitions/model.User'
        type: array
    type: object
host: localhost:8080
info:
  contact: {}
  description: REST API for managing software licenses
  title: License Server API
  version: 0.1.0
paths:
  /admin/users:
    post:
      description: add new user
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      security:
      - ApiKey: []
      summary: Add a user
      tags:
      - users
  /auth/register:
    post:
      description: register new application user
      parameters:
      - description: new user info
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.User'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httputil.HTTPResponse-model_User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Registers a user
      tags:
      - auth
  /auth/token:
    post:
      description: creates a new API key
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httputil.HTTPResponse-model_APIKey'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Creates a token
      tags:
      - auth
schemes:
- http
securityDefinitions:
  ApiKey:
    in: header
    name: X-API-KEY
    type: apiKey
swagger: "2.0"
